---
title: "Analysis_model_runs_afsis_default"
authors: "Soil-climate feedback across sub-Saharan Africa Workshop Participants"
date: "2025-07-23"
output: html_document
---

#Load libraries needed to run MIMICS and Millennial
```{r}
library(FME)
library(here)
library(dplyr) 
library(tidyr)
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(viridis)
library(DT)
library(purrr)
library(Metrics)
library(mlr3)
library(mlr3learners)
library(mlr3viz)
library(mlr3spatial)
library(mlr3spatiotempcv) 
library(iml)
```

#Load model output data and merge with afsis data
```{r}
model_out <- read.csv("./model_output/both_model_results_default_run.csv", row.names = 1) %>%
  #rename SOC column
  dplyr::rename(C_stock_pred_kg_m2 = Soil_Organic_Carbon_kg_m2)

afsis_data <- read.csv("forcing_data/afsis_ref_updated8.csv", as.is=T, , row.names = 1) %>% 
  dplyr::select(SSN, Site, Cluster, Plot, Country, Longitude, Latitude,
                Clay_2um, Clay_8um, Clay_63um, LIG_N, stemp, sm,
                Depth, CORG, pH, bd_extracted, npp_modis,
                Am_Ox_Al, Am_Ox_Fe, Caex, Mgex, Naex, Clay_1_1, Clay_2_1, VegStructure) %>% 
  unite("Country_Site", Country, Site, remove = FALSE) %>% 
  filter(Depth == "Topsoil",
         CORG <= 20) %>% 
  drop_na() %>% 
  #Calculate SOC stocks for observational data (kg/m2)
  mutate(C_stock_obs_kg_m2 = ((CORG/100)*bd_extracted*20)*10)

data_merged <- model_out %>% 
  full_join(afsis_data) %>% 
  #calculate bias
  mutate(C_bias_kg_m2 = C_stock_pred_kg_m2 - C_stock_obs_kg_m2)

#Check for warm samples
afsis_data %>% 
  filter(stemp >= 30) %>% 
  dplyr::count(Site, Country)

```

#Plot predicted vs observed for both models
```{r}

pred_obs <- data_merged %>%
  ggplot(aes(x = C_stock_pred_kg_m2, y = C_stock_obs_kg_m2)) +
  geom_point(aes(color = Country_Site)) +
  scale_x_continuous("Predicted SOC (kg/m2)", expand = c(0,0)) +
  scale_y_continuous("Observed SOC (kg/m2)", expand = c(0,0)) +
  geom_abline(slope = 1) +
  geom_smooth(method = "lm") +
  theme_bw(base_size = 16) +
  theme(legend.position = "none") +
  facet_wrap(~Type, scales = "free_x")
pred_obs
ggsave(paste0("./model_output/Pred_Obs_BothModels_",
              Sys.Date(), ".jpeg"), width = 12, height = 6)

# Interactive plot
# plotly::ggplotly(pred_obs)

lm_mimics <- lm(C_stock_obs_kg_m2 ~ C_stock_pred_kg_m2, 
                data = data_merged %>% filter(Type == "MIMICS"))

summary(lm_mimics)
data_MIMICS = data_merged %>% filter(Type == "MIMICS")
RMSE_MIMICS = sqrt(mean((data_MIMICS$C_stock_obs_kg_m2 - data_MIMICS$C_stock_pred_kg_m2)^2))


lm_millennial <- lm(C_stock_obs_kg_m2 ~ C_stock_pred_kg_m2, 
                    data = data_merged %>% filter(Type == "Millennial"))

summary(lm_millennial)
data_Mill = data_merged %>% filter(Type == "Millennial")
RMSE_Mill = sqrt(mean((data_Mill$C_stock_obs_kg_m2 - data_Mill$C_stock_pred_kg_m2)^2))

```

#Plot model bias against selected soil properties
```{r}
plot_fun_soil_prop <- function(xvar, model){
  data_merged %>% 
    filter(Type == {{model}}) %>% 
    ggplot(aes(y = C_bias_kg_m2, x = {{xvar}})) +
    geom_point(aes(color = Country_Site)) +
    scale_y_continuous("Pred - Obs SOC stocks ") +
    geom_smooth(method = "lm") +
    theme_bw(base_size = 14) +
    theme(legend.position = "none")
}

#MIMICS
mim1 <- plot_fun_soil_prop(model = "MIMICS", xvar = Am_Ox_Al) +
  scale_x_continuous("Oxalate Al (mg/kg)")

mim2 <- plot_fun_soil_prop(model = "MIMICS", xvar = Am_Ox_Fe) +
  scale_x_continuous("Oxalate Fe (mg/kg)")

mim3 <- plot_fun_soil_prop(model = "MIMICS", xvar = Caex) +
  scale_x_continuous("exchangeable Ca (cmol/kg soil)")

mim4 <- plot_fun_soil_prop(model = "MIMICS", xvar = Mgex) +
  scale_x_continuous("exchangeable Mg (cmol/kg soil)")

mim5 <- plot_fun_soil_prop(model = "MIMICS", xvar = pH) +
  scale_x_continuous("pH")

mim6 <- plot_fun_soil_prop(model = "MIMICS", xvar = Clay_63um) +
  scale_x_continuous("Clay < 63 um")

mim7 <- plot_fun_soil_prop(model = "MIMICS", xvar = Clay_1_1) +
  scale_x_continuous("1:1 clays (%)")

mim8 <- plot_fun_soil_prop(model = "MIMICS",xvar = Clay_2_1) +
  scale_x_continuous("2:1 clays (%)")

ggpubr::ggarrange(mim1, mim2, mim3, mim4, mim5, mim6, mim7, mim8)
ggsave(paste0("./model_output/Bias_soil_prop_MIMICS_",
              Sys.Date(), ".jpeg"), width = 12, height = 8)

#Millennial
mil1 <- plot_fun_soil_prop(model = "Millennial", xvar = Am_Ox_Al) +
  scale_x_continuous("Oxalate Al (mg/kg)")

mil2 <- plot_fun_soil_prop(model = "Millennial", xvar = Am_Ox_Fe) +
  scale_x_continuous("Oxalate Fe (mg/kg)")

mil3 <- plot_fun_soil_prop(model = "Millennial", xvar = Caex) +
  scale_x_continuous("exchangeable Ca (cmol/kg soil)")

mil4 <- plot_fun_soil_prop(model = "Millennial", xvar = Mgex) +
  scale_x_continuous("exchangeable Mg (cmol/kg soil)")

mil5 <- plot_fun_soil_prop(model = "Millennial", xvar = pH) +
  scale_x_continuous("pH")

mil6 <- plot_fun_soil_prop(model = "Millennial", xvar = Clay_63um) +
  scale_x_continuous("Clay < 63 um")

mil7 <- plot_fun_soil_prop(model = "Millennial", xvar = Clay_1_1) +
  scale_x_continuous("1:1 clays (%)")

mil8 <- plot_fun_soil_prop(model = "Millennial",xvar = Clay_2_1) +
  scale_x_continuous("2:1 clays (%)")

ggpubr::ggarrange(mil1, mil2, mil3, mil4, mil5, mil6, mil7, mil8)
ggsave(paste0("./model_output/Bias_soil_prop_Millennial_",
              Sys.Date(), ".jpeg"), width = 12, height = 8)
```

#Plot bias vs forcing factors
```{r}
#MIMICS
mim1.1 <- plot_fun_soil_prop(model = "MIMICS", xvar = npp_modis)
mim2.1 <- plot_fun_soil_prop(model = "MIMICS", xvar = Clay_2um)
mim3.1 <- plot_fun_soil_prop(model = "MIMICS", xvar = LIG_N)
mim4.1 <- plot_fun_soil_prop(model = "MIMICS", xvar = stemp)
mim5.1 <- plot_fun_soil_prop(model = "MIMICS", xvar = sm)


ggpubr::ggarrange(mim1.1, mim2.1, mim3.1, mim4.1, mim5.1)
ggsave(paste0("./model_output/Bias_forc_para_MIMICS_",
              Sys.Date(), ".jpeg"), width = 12, height = 8)

# Interactive plot
plotly::ggplotly(mim2.1)

#Millennial
mil1.1 <- plot_fun_soil_prop(model = "Millennial", xvar = pH)
mil2.1 <- plot_fun_soil_prop(model = "Millennial", xvar = bd_extracted)
mil3.1 <- plot_fun_soil_prop(model = "Millennial", xvar = Clay_63um)
mil4.1 <- plot_fun_soil_prop(model = "Millennial", xvar = stemp)
mil5.1 <- plot_fun_soil_prop(model = "Millennial", xvar = sm)
mil6.1 <- plot_fun_soil_prop(model = "Millennial", xvar = npp_modis)


ggpubr::ggarrange(mil1.1, mil2.1, mil3.1, mil4.1, mil5.1, mil6.1)
ggsave(paste0("./model_output/Bias_forc_para_Millennial_",
              Sys.Date(), ".jpeg"), width = 12, height = 8)

# Interactive plot
plotly::ggplotly(mil3.1)

```

#Plot bias vs spatial
```{r}

plot_fun_spatial <- function(xvar){
  data_merged %>% 
    ggplot(aes(y = C_bias_kg_m2, x = {{xvar}})) +
    geom_point(aes(color = Country_Site)) +
    scale_y_continuous("Pred - Obs SOC stocks ") +
    geom_smooth(method = "lm") +
    theme_bw(base_size = 14) +
    theme(legend.position = "none") +
    facet_wrap(~Type)
}

p1 <- plot_fun_spatial(xvar = Latitude)
p2 <- plot_fun_spatial(xvar = Longitude)

ggpubr::ggarrange(p1, p2, nrow = 2)
ggsave(paste0("./model_output/Bias_spatial_MIMICS_Millennial_",
              Sys.Date(), ".jpeg"), width = 12, height = 10)

# data_merged %>% 
#   ggplot(aes(x = Longitude, y = Am_Ox_Al)) +
#   geom_point(aes(color = Site)) +
#   geom_smooth(method = "lm") +
#   theme_bw(base_size = 14) +
#   theme(legend.position = "none")

```

# Random Forest Analysis - based on predicted C stocks for AfSIS data
```{r}
# Select variables 
afsis_mimics_rf <- data_merged %>% 
  unite("id", Country:Cluster) %>%
  mutate(npp_modis.gC.m2.yr = npp_modis*1000) %>% 
  dplyr::select(id, npp_modis.gC.m2.yr, Clay_2um, LIG_N, stemp, sm, C_stock_pred_kg_m2)

afsis_millennial_rf <- data_merged %>%
  unite("id", Country:Cluster) %>%
  mutate(npp_modis.gC.m2.d = npp_modis*1000/365) %>%
  dplyr::select(id, npp_modis.gC.m2.d, Clay_63um, pH, stemp, sm, C_stock_pred_kg_m2)

## MIMICS
mimics_task_rf <- as_task_regr(x = afsis_mimics_rf,
                               target = "C_stock_pred_kg_m2")

mimics_lrn_rf <- lrn("regr.ranger", importance = "permutation",
                     num.trees = 1000)

# Add id as group for CV (same id kept together)
mimics_task_rf$set_col_roles("id", roles = "group")
print(mimics_task_rf)

# cross-validation
set.seed(42)
resampling <- rsmp("cv", folds = 10)
resampling$instantiate(mimics_task_rf)

## Train model & check performance
mimics_rf <- mlr3::resample(task = mimics_task_rf, learner = mimics_lrn_rf, 
                            resampling = resampling, store_models = TRUE)

# R2 = 0.30, mae = 7.31, rmse = 8.94
mimics_rf$aggregate(measures = msrs(c("regr.rsq", "regr.mae", "regr.rmse")))

mimics_rf_pred <- mimics_rf$prediction(predict_sets = "test")
mimics_rf_pred_df <- data.frame(truth = mimics_rf_pred$truth,
                                response = mimics_rf_pred$response)

mimics_rf_pred_df %>% 
  ggplot(aes(x = response, y = truth)) +
  geom_point(size = 1) +
  geom_rug(length = unit(0.25, "cm")) +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_smooth(method = "lm") +
  theme_bw(base_size = 16) +
  theme(axis.text = element_text(color = "black")) +
  scale_y_continuous("Observed SOC stocks [kg/m2]", 
                     limits = c(0,63), expand = c(0,0)) +
  scale_x_continuous("Predicted SOC stocks [kg/m2]", 
                     limits = c(0,63), expand = c(0,0))
ggsave(paste0("./model_output/RF_PredictedAfSIS_MIMICS_obs_pred_cv_10f_",
              Sys.Date(), ".jpeg"), width = 6, height = 6)

mimics_vi <- lapply(mimics_rf$learners, function(x) x$model$variable.importance)

mimics_vi_df <- mimics_vi %>%
  plyr::ldply() %>%
  pivot_longer(everything(), names_to = "variable", values_to = "x") %>%
  summarise(median = median(x, na.rm = TRUE),
            mad    = mad(x, na.rm = TRUE),
            .by = variable) %>%
  arrange(median) %>% 
  mutate(median_pct = (median / sum(median, na.rm = TRUE)) * 100,
         mad_pct = (mad / sum(median, na.rm = TRUE)) * 100) 

mimics_vi_df %>% 
  ggplot(aes(x = reorder(variable, -median_pct), y = median_pct)) +
  geom_col() +
  geom_errorbar(aes(ymin = median_pct - mad_pct,
                    ymax = median_pct + mad_pct),
                width = 0.15) +
  theme_bw(base_size = 16) +
  theme(axis.text = element_text(color = "black")) +
  scale_x_discrete("") +
  scale_y_continuous("Relative explained variation (%)", expand = c(0,0),
                     limits = c(0,35))
ggsave(paste0("./model_output/RF_PredictedAfSIS_MIMICS_vi_cv_10f_",
              Sys.Date(), ".jpeg"), width = 8, height = 6)

## Partial dependence plots
mimics_task_rf_pdp <- as_task_regr(x = afsis_mimics_rf %>% 
                                     dplyr::select(-id),
                                   target = "C_stock_pred_kg_m2")

mimics_lrn_rf_pdp <- lrn("regr.ranger", importance = "permutation",
                         num.trees = 1000) 

set.seed(42)
mimics_lrn_rf_pdp$train(mimics_task_rf_pdp)

mimics_model_rf <- Predictor$new(mimics_lrn_rf_pdp, data = afsis_mimics_rf %>% 
                                   dplyr::select(-id))

#PDP
mimics_effect_rf_pdp <- FeatureEffects$new(mimics_model_rf, method = "pdp",
                                           features = c("npp_modis.gC.m2.yr", 
                                                        "Clay_2um",
                                                        "LIG_N", "stemp", "sm"))

plot(mimics_effect_rf_pdp)
ggsave(paste0("./model_output/RF_PredictedAfSIS_MIMICS_pdp_",
              Sys.Date(), ".jpeg"), width = 10, height = 6)

## Millennial
millennial_task_rf <- as_task_regr(x = afsis_millennial_rf,
                                   target = "C_stock_pred_kg_m2")

millennial_lrn_rf <- lrn("regr.ranger", importance = "permutation",
                         num.trees = 1000)

# Add id as group for CV (same id kept together)
millennial_task_rf$set_col_roles("id", roles = "group")
print(millennial_task_rf)

# cross-validation
set.seed(42)
resampling <- rsmp("cv", folds = 10)
resampling$instantiate(millennial_task_rf)

## Train model & check performance
millennial_rf <- mlr3::resample(task = millennial_task_rf, learner = millennial_lrn_rf, 
                                resampling = resampling, store_models = TRUE)

# R2 = 0.28, mae = 7.31, rmse = 9.06
millennial_rf$aggregate(measures = msrs(c("regr.rsq", "regr.mae", "regr.rmse")))

millennial_rf_pred <- millennial_rf$prediction(predict_sets = "test")
millennial_rf_pred_df <- data.frame(truth = millennial_rf_pred$truth,
                                    response = millennial_rf_pred$response)

millennial_rf_pred_df %>% 
  ggplot(aes(x = response, y = truth)) +
  geom_point(size = 1) +
  geom_rug(length = unit(0.25, "cm")) +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_smooth(method = "lm") +
  theme_bw(base_size = 16) +
  theme(axis.text = element_text(color = "black")) +
  scale_y_continuous("Observed SOC stocks [kg/m2]", 
                     limits = c(0,63), expand = c(0,0)) +
  scale_x_continuous("Predicted SOC stocks [kg/m2]", 
                     limits = c(0,63), expand = c(0,0))
ggsave(paste0("./model_output/RF_PredictedAfSIS_Millennial_obs_pred_cv_10f_",
              Sys.Date(), ".jpeg"), width = 6, height = 6)

millennial_vi <- lapply(millennial_rf$learners, function(x) x$model$variable.importance)

millennial_vi_df <- millennial_vi %>%
  plyr::ldply() %>%
  pivot_longer(everything(), names_to = "variable", values_to = "x") %>%
  summarise(median = median(x, na.rm = TRUE),
            mad    = mad(x, na.rm = TRUE),
            .by = variable) %>%
  arrange(median) %>% 
  mutate(median_pct = (median / sum(median, na.rm = TRUE)) * 100,
         mad_pct = (mad / sum(median, na.rm = TRUE)) * 100) 

millennial_vi_df %>% 
  ggplot(aes(x = reorder(variable, -median_pct), y = median_pct)) +
  geom_col() +
  geom_errorbar(aes(ymin = median_pct - mad_pct,
                    ymax = median_pct + mad_pct),
                width = 0.15) +
  theme_bw(base_size = 16) +
  theme(axis.text = element_text(color = "black")) +
  scale_x_discrete("") +
  scale_y_continuous("Relative explained variation (%)", expand = c(0,0),
                     limits = c(0,35))
ggsave(paste0("./model_output/RF_PredictedAfSIS_Millennial_vi_cv_10f_",
              Sys.Date(), ".jpeg"), width = 8, height = 6)

## Partial dependence plots
millennial_task_rf_pdp <- as_task_regr(x = afsis_millennial_rf %>% 
                                         dplyr::select(-id),
                                       target = "C_stock_pred_kg_m2")

millennial_lrn_rf_pdp <- lrn("regr.ranger", importance = "permutation",
                             num.trees = 1000) 

set.seed(42)
millennial_lrn_rf_pdp$train(millennial_task_rf_pdp)

millennial_model_rf <- Predictor$new(millennial_lrn_rf_pdp, data = afsis_millennial_rf %>% 
                                       dplyr::select(-id))

#PDP
millennial_effect_rf_pdp <- FeatureEffects$new(millennial_model_rf, method = "pdp",
                                               features = c("npp_modis.gC.m2.d", 
                                                            "Clay_63um",
                                                            "pH", "stemp", "sm"))

plot(millennial_effect_rf_pdp)
ggsave(paste0("./model_output/RF_PredictedAfSIS_Millennial_pdp_",
              Sys.Date(), ".jpeg"), width = 10, height = 6)
```

