---
title: "Century_sensitivity_analysis.Rmd"
author: "Rose Abramoff, Katie Rocci, Simon Heinberg, Sophie von Fromm"
output: html_document
date: "2025-09-17"
---

#Load libraries 
```{r}
library(readxl)
library(tidyr)
library(dplyr)
library(corrplot)
library(here)
library(purrr)
```

#Read in SSA data and load Century components
```{r}
#load century model components
source(here("functions/run_functions_Century.R")) #R script that contains calls to run model
source(here("ODEs/derivs_Century.R")) #Century ODEs

## AfSIS data
forcing_data <- read.csv("forcing_data/sensitivity_analysis_simulated_input_data_2025-11-18.csv", 
                         as.is = T)

#match Millennial names
# Forcing data Century
# https://search.r-project.org/CRAN/refmans/SoilR/html/CenturyModel.html

forcing_data_Century <- forcing_data %>%
  mutate(npp_modis.gC.m2.d = npp_modis*1000/365) %>%
  drop_na(npp_modis.gC.m2.d, Clay_2um, Clay_63um, stemp, 
          sm, pH, bd_extracted, LIG_N) %>%
  mutate(param_claysilt = Clay_63um/100, #fraction in Century
         forc_st = stemp, 
         forc_sw = sm, 
         forc_npp = npp_modis.gC.m2.d,
         LN = LIG_N, 
         LigFrac = LIG/100,
         input_to_metlitter = 0.85 - 0.013 * LN,
         site_id = row_number()) %>% 
  dplyr::select(Longitude, Latitude, param_claysilt, forc_st, forc_sw, forc_npp,
                LN, LigFrac, input_to_metlitter, site_id)


```


#load parameter changes (if needed)
```{r}
# Read in parameters - Described in Table A1 of Abramoff et al. (2021)
parameters.file <- read.table(here("parameters/soilpara_in_fit_SSA_Century.txt")) #fitted
parameters <- as.list(parameters.file$V2)
names(parameters) <- parameters.file$V1
```

#Sensitivity analysis
```
In this sensitivity analysis, our overall objective is to understand how Century output varies over the full range of data available in the AfSIS dataset
```
##Run input data combinations for all models
```{r}
Start.Timer <- Sys.time()

# Function to run model for one row of site parameters
run_model_for_site <- function(site_row, base_params) {
  # Copy full parameter list
  site_params <- as.list(base_params)
  # Override default site-specific value with values from AfSIS
  site_params$input_to_metlitter <- as.numeric(site_row$input_to_metlitter)
  site_params$param_claysilt <- as.numeric(site_row$param_claysilt)
  site_params$LigFrac <- as.numeric(site_row$LigFrac)
    
# Format input data
input_for_site <- data.frame(
  forc_st  = rep(as.numeric(site_row$forc_st), 365),
  forc_sw  = rep(as.numeric(site_row$forc_sw), 365),
  forc_npp = rep(as.numeric(site_row$forc_npp), 365),
  stringsAsFactors = FALSE
)

# Run the model with an error-catching wrapper
  result <- tryCatch({
    Solve_Model_Century(input_for_site, derivs_Century, site_params)
  }, error = function(e) {
    warning(paste("Model failed for site:", site_row$site_id, ":", e$message))
    return(NULL)
  })

  if (is.null(result)) return(NULL)

  pool_df <- as.data.frame(t(result$y))
  pool_df$site_id <- site_row$site_id
  return(pool_df)
}

# Apply model across all rows of the site parameter dataframe
results_list <- apply(forcing_data_Century, 1, function(row) {
  row <- as.list(row)  # Convert row to list for easy referencing
  run_model_for_site(row, parameters)
})

# Combine all into one dataframe
Century_ss <- dplyr::bind_rows(results_list)


# Merge model outputs with original site parameters if needed
Century_ss_AllSites <- forcing_data_Century %>%
  left_join(Century_ss, by = "site_id") %>%
  mutate(Soil_Organic_Carbon_kg_m2 = (StrLitter + MetLitter + ACTIVE + SLOW + PASSIVE) / 1000)

write.csv(Century_ss_AllSites, row.names = FALSE,
          paste0("./model_output/Century_SensitivityAnalysisOutput_",
                 Sys.Date(), ".csv"))

End.Timer <- Sys.time()
End.Timer - Start.Timer
```


