---
title: "Fit_Millennial.Rmd"
output: html_document
date: "2025-07-22"
authors: "R Abramoff and Katie Rocci"
---

#Load libraries, data, model files
```{r}
#load libraries
library(FME)
library(here)
library(caret)
library(dplyr)
library(tidyr)

##load forcing data
forcing_data <- read.csv("forcing_data/afsis_ref_updated8.csv", as.is=T)
forcing_data <- forcing_data[,-c(1,2,4)] # Fix for first column name import error

forcing_data_Millennial <- forcing_data %>% 
                                   drop_na(Litterfall.gC.m2.yr, NPP.gC.m2.d, Clay_2um, Clay_63um, SoilTMP_C, SoilMoi_m3m3, pH, bd_extracted, LIG_N) %>%
  mutate(npp_modis_gC.m2.yr = npp_modis*1000) %>% 
  mutate(forc_npp = npp_modis_gC.m2.yr/365) %>% 
                                   dplyr::select(param_pH = pH,
                                   param_bulkd = bd_extracted, 
                                   param_claysilt = Clay_63um, 
                                   forc_st = stemp, 
                                   forc_sw = sm, 
                                   forc_npp,
                                   Latitude,
                                   Longitude,
                                   Depth,
                                   SSN_row_ID = X,
                                   CORG) %>% 
                            mutate(Soil_Organic_Carbon_kg_m2 = CORG*10*param_bulkd*20/100) %>%
                            mutate(param_bulkd = param_bulkd*1000*0.2)  %>% #1000 converts from g/cm3 to kg/m3, 0.2 for top 20 cm
                                  filter(Depth == "Topsoil", CORG <= 20)

#define observed SOC as a dataframe
SOC_obs <- forcing_data_Millennial %>% select(Soil_Organic_Carbon_kg_m2, SSN_row_ID)

#load millennial model components
source(here("functions/run_functions.R")) #R script that contains calls to run model
source(here("ODEs/derivs_V2_MM.R")) #The official version of Millennial V2

#load default parameters - Described in Table A1 of Abramoff et al. (2021)
parameters.file <- read.table(here("parameters/soilpara_in_fit_with_qmax.txt"))
parameters <- as.list(parameters.file$V2)
names(parameters) <- parameters.file$V1
```

#Partition training data
```{r}
proptrain = 0.8

#Partitions data into training and test datasets
set.seed(1)
trainIndex <- createDataPartition(SOC_obs$Soil_Organic_Carbon_kg_m2, p = proptrain, list = FALSE, times = 1)
obsTrain <- SOC_obs[trainIndex,]
obsTest <- SOC_obs[-trainIndex,]  

inputsTrain <- forcing_data_Millennial[trainIndex,]
inputsTest <- forcing_data_Millennial[-trainIndex,]

Obs.pools <- obsTrain
inputs <- inputsTrain
```

#Scaling function
```{r}
rescale_multiply_restore <- function(x, factor = 1.5) {
  # Step 1: Save original min and max
  x_min <- min(x, na.rm = TRUE)
  x_max <- max(x, na.rm = TRUE)
  
  # Avoid divide-by-zero error
  if (x_max == x_min) {
    warning("All values are equal. Returning original vector.")
    return(x)
  }
  
  # Step 2: Normalize to [0, 1]
  x_scaled <- (x - x_min) / (x_max - x_min)
  
  # Step 3: Multiply by fixed factor
  x_scaled_mod <- x_scaled * factor
  
  # Optional: clamp values to [0, 1] if factor pushes them out of bounds
  x_scaled_mod <- pmax(pmin(x_scaled_mod, 1), 0)
  
  # Step 4: Rescale back to original range
  x_rescaled <- x_scaled_mod * (x_max - x_min) + x_min
  
  return(x_rescaled)
}
```

#Parameters to fit
```{r}
parToFit.pools <- c(eact_pl = parameters$eact_pl, alpha_pl = parameters$alpha_pl, tae_ref = parameters$tae_ref)

parToFit.lower <- parToFit.pools*0.5

parToFit.upper <- parToFit.pools*1.5
```

#Define cost function
```{r}
# Definition of the cost function
Objective.pools <- function(x, parset = names(x)) {
  parameters[parset] <- x
  out <- Solve_Model_for_Fit(inputsTrain, parameters)
  modCost(out, Obs.pools, x="SSN_row_ID", weight = "none")
}
```

#Run model fit
```{r}
start_time = Sys.time()
# Fit the model
set.seed(123)
Fit.pools <- modFit(
  f = Objective.pools,
  p = parToFit.pools,
  lower = parToFit.lower,
  upper = parToFit.upper,
  method = "Marq", #BFGS #Marq
  jac = NULL,
  control = list(
    ftol = 1e-06,
    ptol = 1e-06,
    gtol = 1e-06,
    nprint = 1
  ),
  hessian = TRUE
)
end_time = Sys.time()
fit.time <- end_time - start_time
fit.time

# Save the best parameters as a table
outtab <- cbind(Fit.pools$par, parToFit.lower, parToFit.pools, parToFit.upper)
colnames(outtab) <- c("FitPars","Lower","Default","Upper")
write.csv(outtab, file= here("parameter_fit_SSA.csv"))
```

#Cross-validation on testing set
```{r}
#Get best parameters
parameters[names(parToFit.pools)] <- Fit.pools$par
#Calculate model pools at testing sites
optim.test <- Solve_Model_for_Fit(inputsTest, parameters)

#Calculate model performance indices
##Bias is modeled - observed
fit.SOM <- summary(lm(optim.test[1:dim(inputsTest)[1],]$Soil_Organic_Carbon_kg_m2 ~ obsTest$Soil_Organic_Carbon_kg_m2))
SOM.bias <- optim.test[1:dim(inputsTest)[1],]$Soil_Organic_Carbon_kg_m2 - obsTest$Soil_Organic_Carbon_kg_m2
dim.SOM <- dim(inputsTest)[1]
RMSE_kg <- sqrt(sum((obsTest$Soil_Organic_Carbon_kg_m2- optim.test[1:dim.SOM,]$Soil_Organic_Carbon_kg_m2)^2, na.rm=T)/dim.SOM)
AIC <- dim.SOM * log(sum((obsTest$Soil_Organic_Carbon_kg_m2- optim.test[1:dim.SOM,]$Soil_Organic_Carbon_kg_m2)^2, na.rm=T)/dim.SOM) + 2*length(parameters[[3]])
MBE_SOM <- mean(SOM.bias, na.rm=T)
MAE_SOM <- mean(abs(SOM.bias), na.rm=T)
print(list(RMSE_kg = RMSE_kg,AIC = AIC, MAE_SOM = MAE_SOM, MBE_SOM = MBE_SOM, fit.SOM= fit.SOM))
write.csv(as.data.frame(unlist(list(FitPars = Fit.pools$par, RMSE_kg = RMSE_kg,AIC = AIC, MAE_SOM = MAE_SOM, MBE_SOM = MBE_SOM, df1= fit.SOM$fstatistic[2], df2= fit.SOM$fstatistic[3], Fstat=fit.SOM$fstatistic[1], adjR2=fit.SOM$adj.r.squared))), file=paste0("ParFitResult_",Sys.time(),".csv"))
```

#Run Best Parameters
```{r}
# Recover the optimized parameters and plot the results
start_time = Sys.time()

parameters[names(parToFit.pools)] <- Fit.pools$par
optim.pools <- Solve_Model_for_Fit(forcing_data_Millennial, parameters)

end_time = Sys.time()
optim.time <- end_time - start_time

ymax_plot <- ceiling(max(max(SOC_obs$Soil_Organic_Carbon_kg_m2, na.rm=T), max(optim.pools$Soil_Organic_Carbon_kg_m2, na.rm=T)))
ymax_plot <- ifelse(ymax_plot>100, 20, ymax_plot)

#pdf(file="fit_Millennial_AfSIS.pdf", height=4, width=4)
par(mfrow = c(1,1))
par(mar = c(3.5,3.7,0,0)+.9)
par(oma = c(0,0,0,0))
plot(optim.pools$Soil_Organic_Carbon_kg_m2, SOC_obs$Soil_Organic_Carbon_kg_m2, ylab = expression("Observed OM (kg " ~ m^{2} ~ ")"), xlab = expression("Predicted OM (kg " ~ m^{2} ~ ")"), lwd = 2, type = "p", col = "black", ylim=c(0,ymax_plot), xlim=c(0,ymax_plot))
legend("topright", c("SOM"), col=c("black"), pch=16)
#dev.off()
```

